### PR TITLE
Make fact gluster_host suppress the error output, if Resolv.getaddres…

### PR DESCRIPTION
**Pull request by derjohn**
…s does not work at all, e.g. DNS setup not complete during provision.

Better version :)

### CODE REVIEW

**Comment by purpleidea** [comment]
@derjohn Did you test this patch? I doubt it would work...

```
$ irb
2.0.0-p451 :001 > x.nil?
NameError: undefined local variable or method `x' for main:Object
	from (irb):1
```

**Comment by purpleidea** [comment]
Hey @derjohn did you want to review and resubmit, or should I close this?

Thanks

**Comment by derjohn** [comment]
Hello,
you can probably close this. I switched to a different gluster module (I need ubuntu support) and thus can't test anymore.

rgds,
j.

**Comment by purpleidea** [comment]
@derjohn Okay, closed.

Although FYI, this should work with ubuntu very easily, as we use this technique for multi os support: https://ttboj.wordpress.com/2014/06/04/hiera-data-in-modules-and-os-independent-puppet/

Cheers.

**Pull request closed without merging**
