### PR TITLE
Add Gluster 3.6.1 compatibility for CentOS 6.6

### PR DESCRIPTION
**Pull request by jackdpeterson**
#help resolve repeated modification to

--- /var/lib/glusterd/glusterd.info
@@ -1,2 +1 @@
 UUID=abc.def.xyz
-operating-version=1

### CODE REVIEW

**Comment by jackdpeterson** [comment]
Yeah, it's 30600 ... setting to 30601 causes glusterd to not restart properly :-\ ... I'm not sure how exactly to achieve the version check inside of the OS-independent vars yet. I'll poke around a bit more to see what I can figure out.

**Comment by jackdpeterson** [comment]
Verification requested that this doesn't blow things up on Non-CentOS 6.6 boxes. puppet ran successfully for me with these changes as os-indepdendent yank add-ons. I put this as exclusively for 6.6 because I know there are issues on that specific version. Don't know about other CenOS releases though.

**Comment by jackdpeterson** [comment]
For non-IRC users and future reference:

‹jackdpeterson›
[11:59:51]@purpleidea cc JoeJulian https://gist.github.com/jackdpeterson/aad48879a9c2e02f0882 
‹partner›
[12:07:12]i can confirm the version is 30600 on debian jessie aswell for 3.6.1 
[12:08:53]and if i manually edit it to 30601 as was done on gist link the symptoms are the same ie. fails to start up the daemon

**Comment by purpleidea** [comment]
@jackdpeterson This all looks great, but there are two separate features across six different commits. Please squash the respective four and two commits down to two separate commits, clean up the typos, and it's ready to merge. Additionally, I added this patch:

diff --git a/data/params/RedHat/CentOS/6.6.yaml b/data/params/RedHat/CentOS/6.6.yaml
index 06b94f7..daceac7 100644
--- a/data/params/RedHat/CentOS/6.6.yaml
+++ b/data/params/RedHat/CentOS/6.6.yaml
@@ -1,10 +1,8 @@
 # gluster/data/params/RedHat/CentOS/6.6.yaml
 ---
-# looks like this may be irrelevant after all as  CentOS 6.6 
-# appears to accept system_u; however, it required a reboot for 
-# puppet to stop looping through modifying files on each iteration.
-gluster::params::selinux_glusterd_seluser: 'system_u'  
+# looks like this may be irrelevant after all, as CentOS 6.6 appears to accept
+# system_u; however, it required a reboot for puppet to stop looping through
+# and modifying files on each iteration.
+gluster::params::selinux_glusterd_seluser: 'system_u'
 
-
-
-# vim: ts=8
\ No newline at end of file
+# vim: ts=8
diff --git a/data/versions/3.6.1.yaml b/data/versions/3.6.1.yaml
index 02bef3c..96f08fb 100644
--- a/data/versions/3.6.1.yaml
+++ b/data/versions/3.6.1.yaml
@@ -1,4 +1,5 @@
 # gluster/data/versions/3.6.1.yaml
 ---
+# NOTE: this is the correct version, although it might have been a dev mistake!
 gluster::versions::operating_version: '30600'   # v3.6.1
 # vim: ts=8

Which you're welcome to either incorporate into your squashed commit, or I can add it on afterwards.

Thanks!

**Comment by jackdpeterson** [comment]
Commits squashed... not sure about your patch.

**Comment by purpleidea** [comment]
@jackdpeterson This is now merged. Thanks!

I hope you don't mind some feedback:
The problem with your patches was that you "made a mistake" in one, that you "fixed" in the other. The beauty of your patch still being on a branch, and not in my git master, means you can use git to "hide" all those mistakes that are caught in patch review. Additionally, you can fundamentally separate unrelated concepts into separate commits.

There were also some extra white space chars and things like that which we're not needed. Additionally 3.6.1 was in the wrong folder, and wouldn't have worked where it was.

After squashing your two commits (to hide the mistakes) you can see my changes as: https://github.com/purpleidea/puppet-gluster/commit/96304dcd6a7655e7f7fc63b9dfe98a24fced4ae7

I hope you send more patches, and try and follow those guidelines next time :)

Cheers!

**Comment by jackdpeterson** [comment]
Thanks for the feedback and accepting the pull request :-) I'll give those
guidelines a shot. Learned a new skill too in the process -- squashing
commits.

Cheers

On Mon, Jan 19, 2015 at 3:58 PM, James <notifications@github.com> wrote:

> Closed #25 <https://github.com/purpleidea/puppet-gluster/pull/25>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purpleidea/puppet-gluster/pull/25#event-221310403>.
>



-- 
Jack Peterson
Jack.Peterson@gmail.com
(425) 372 - 8514 (Cell)

**Comment by purpleidea** [comment]
On Mon, Jan 19, 2015 at 7:07 PM, Jack Peterson <notifications@github.com>
wrote:

> Thanks for the feedback and accepting the pull request :-) I'll give those
> guidelines a shot. Learned a new skill too in the process -- squashing
> commits.
>
> Cheers
>

Sweet... Git will come pretty naturally after using it for a while and
forcing yourself to fix/change patches, etc... git rebase -i <commit> is
your friend :)

Cheers

PS:
https://twitter.com/purpleidea/status/557329152974815232

**Pull request closed without merging**
