### PR TITLE
add support for creating gluster with an arbiter

### PR DESCRIPTION
**Pull request by pulecp**

### CODE REVIEW

**Comment by purpleidea** [comment]
@pulecp This looks great... I'm quite pleased to not have to nitpick this patch, thanks!

I am happy to merge as-is, but I will add two optional comments:

1) If you add a docs patch with this, I'll be happy. At least add an examples/arbiter.pp file...
2) On a more technical note: have you tested this or thought about how it might work in conjunction with gluster::simple ? If not, no biggie, but probably worth considering.

Cheers!

**Comment by pulecp** [comment]
Hi @purpleidea,

1) I added the new example what is probably better because an arbiter is a new feature and I guess that not everyone will want to use it "as default". Also some features with an arbiter are still not developed as add an arbiter to the running cluster with 2 nodes.

2) I was thinking about it but I noticed that gluster::simple is using some automagic which will collect all bricks. And the order of bricks is random. But the order of bricks is crucial for Gluster with an arbiter. So I think that this automagic feature would have to be reimplemented with some "arbiter flag".

Greetings

**Comment by purpleidea** [comment]
Cool, LGTM, Merged.

If you want to hack on the gluster::simple issues, LMK.

Cheers!

**Comment by purpleidea** [comment]
This was merged in https://github.com/purpleidea/puppet-gluster/commit/69d03aa824d7daf00a6a7c7bbfc7ec9ef159d394

Don't know why github is stupid and left this open. Closing...

**Pull request closed without merging**
