### PR TITLE
add option repo in gluster::wrapper class

### PR DESCRIPTION
**Pull request by pulecp**

### CODE REVIEW

**Comment by purpleidea** [comment]
@pulecp gluster::wrapper should probably be deprecated, but if it still has use to you, then I don't mind adding this patch...

However, bump up the repo arg one line for both uses and use the correct tab formatting as elsewhere in the project.

Cheers!

**Comment by pulecp** [comment]
Okay, then what is the best example which I could use? I guess
https://github.com/purpleidea/puppet-gluster/blob/master/examples/filesystem-backed-bricks-example.pp,
then my patch is unnecessary.

I am surprised by the formatting. I didn't care when I saw my puppet-lint
complaing about every line. I will set up my vim next time.

Greetings

**Comment by purpleidea** [comment]
@pulecp I recommend you start with gluster::simple

HTH,
Cheers!

**Comment by pulecp** [comment]
One more question if I can ask in this thread.

Is it possible to deploy one host as arbiter?

**Comment by purpleidea** [comment]
On Tue, Jul 21, 2015 at 3:29 AM, Pavel Pulec <notifications@github.com>
wrote:

> One more question if I can ask in this thread.
>
> Is it possible to deploy one host as arbiter?
>


Not quite sure what this means. Read through many of the blog posts and
documentation, and if you still don't the answer, then LMK. There is also
at least one screencast.

Cheers,
James

**Comment by pulecp** [comment]
The arbiter is a host which keeps only filenames and metadata. The arbiter
is there to keep quorum so you can have 3 hosts where only 2 keep data (it
saves some space).

http://gluster.readthedocs.org/en/latest/Features/afr-arbiter-volumes/

Greetings,
Pavel

**Comment by purpleidea** [comment]
On Tue, Jul 21, 2015 at 3:38 AM, Pavel Pulec <notifications@github.com>
wrote:

> The arbiter is a host which keeps only filenames and metadata. The arbiter
> is there to keep quorum so you can have 3 hosts where only 2 keep data (it
> saves some space).
>
> http://gluster.readthedocs.org/en/latest/Features/afr-arbiter-volumes/
>


Never tried this. Puppet-Gluster would need a patch to support this.
Test it and see if it works first.

Cheers,
James

**Comment by pulecp** [comment]
@purpleidea I moved from _gluster::simple_ to particular gluster classes and it seems that everything working very well. Good job!

Could I ask how difficult would be to add the support for an arbiter?

**Comment by purpleidea** [comment]
On Fri, Jul 24, 2015 at 4:20 AM, Pavel Pulec <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> I moved from *gluster::simple*
> to particular gluster classes and it seems that everything working very
> well. Good job!
>
> Could I ask how difficult would be to add the support for an arbiter?
>

I never tried the arbiter feature, but at first glance it looks
straightforward... So this probably would be an easy puppet-gluster patch
but having not gotten into it, nor knowing the scope of the feature, I
can't tell for sure.

Good luck!

**Pull request closed without merging**
