### PR TITLE
Add nobootwait mount options for bricks by default

### PR DESCRIPTION
**Pull request by jackdpeterson**
AWS-optimized fix -- Add nobootwait by default to a given mount. This pull request is to help ensure that the system can properly boot despite a failed EBS-backed brick. This is probably a best practice to allow for maintenance activity on a failed brick to occur once SSH has been fully loaded, etc.

Let me know if there is a need for a documentaiton update.

Thanks

### CODE REVIEW

**Comment by purpleidea** [comment]
@jackdpeterson Hi Jack, Thanks for the patch!

Two comments:
1) Should this be configurable, or does *everyone* always want this on? (aws or not)

2) Can you rebase your patch so that it has a single line title, and then a separate multi-line description... Using an ellipsis is probably not a good git practice ;)

Cheers!

**Comment by semiosis** [comment]
Every ubuntu glusterfs client wants this option in fstab.  If it's missing, and the glusterfs mount fails, then the boot will hang.  If it's present then boot continues without that mount point.

**Comment by purpleidea** [comment]
@semiosis Any reason you expect this to be different on RPM based systems, arch or elsewhere?

**Comment by purpleidea** [comment]
I'll merge this as soon as someone can confirm it works on RPM based systems.

**Comment by jackdpeterson** [comment]
@semiosis The main reason why I commented that this is an AWS specific optimization is that it is very difficult to diagnose hung instances on AWS than other providers that provide direct console access to bypass boots that hang and require manual intervention. I don't see why this would be an issue. Furthermore, the instance that I was testing this on was actually CentOS 6.x. so that should cover the RPM side of things.

**Comment by semiosis** [comment]
I thought nobootwait was ubuntu specific.  But *I* am pretty much ubuntu specific these days, so I wouldn't know otherwise.

**Comment by purpleidea** [comment]
@jackdpeterson This article:

http://www.sgvulcan.com/centos-6-x-misses-nobootwait-fstab-option/

Seems to suggest that it *won't* work on CentOS. So I think we need to update this patch to have it configurable via data-in-modules. Patch should be fairly straightforward, but it's not as simple as this one-liner, sorry.

**Comment by jackdpeterson** [comment]
I can confirm this breaks CentOS (Fedora) based systems on clean provision...

dmesg | tail...

Adding 16118780k swap on /mnt/swap.1.  Priority:-1 extents:169 across:19554300k SS
SGI XFS with ACLs, security attributes, large block/inode numbers, no debug enabled
SGI XFS Quota Management subsystem
XFS (dm-0): unknown mount option [nobootwait].

**Comment by purpleidea** [comment]
On Tue, Mar 3, 2015 at 3:43 PM, Jack Peterson <notifications@github.com>
wrote:

> I can confirm this breaks CentOS (Fedora) based systems on clean
> provision...
>
> dmesg | tail...
>
> Adding 16118780k swap on /mnt/swap.1. Priority:-1 extents:169
> across:19554300k SS
> SGI XFS with ACLs, security attributes, large block/inode numbers, no
> debug enabled
> SGI XFS Quota Management subsystem
> XFS (dm-0): unknown mount option [nobootwait].
>


Thanks for confirming!

**Comment by purpleidea** [comment]
If you are uncomfortable with the technique on how to do os-independent puppet (and update this patch to make it easy to add this in in a sane way) you can read this article:
https://ttboj.wordpress.com/2014/06/04/hiera-data-in-modules-and-os-independent-puppet/

I'm happy to review/help if you need.
Cheers

**Comment by jackdpeterson** [comment]
@purpleidea The one issue I found when adding to options_list (maybe I did something incorrectly) was that it wouldn't properly format the partition. I'll take a second look at that and see if I can do that as it would be much simpler!

**Comment by purpleidea** [comment]
@jackdpeterson What do you mean it "wouldn't properly format the partition" ?

**Comment by purpleidea** [comment]
@jackdpeterson Unfortunately, there are two commits and/or they are not rebased to git master.

Proof:

$ git pull https://github.com/jackdpeterson/puppet-gluster.git master
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/jackdpeterson/puppet-gluster
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 data/params/Debian.yaml | 4 ++++
 manifests/brick.pp      | 8 +++++---
 manifests/params.pp     | 3 +++
 3 files changed, 12 insertions(+), 3 deletions(-)

$ git log|head -13
commit 68be8ff14f39d49e75d32dbcff9874aca1876ea4
Merge: ae24ecc 803dd2c
Author: James Shubin <purpleidea@redhat.com>
Date:   Fri Mar 6 20:49:29 2015 -0500

    Merge branch 'master' of https://github.com/jackdpeterson/puppet-gluster into jackdpeterson-master

commit 803dd2c4e00273948205a2827706905dd608bfac
Author: Jack D Peterson <jack.peterson@gmail.com>
Date:   Fri Mar 6 15:32:17 2015 -0800

    Add nofail for RHEL and nobootwait for Debian based OS mount parameters.

**Comment by purpleidea** [comment]
If it's confusing, you can close this PR and open a new one.

**Pull request closed without merging**
