### PR TITLE
Add nofail and nobootwait for respective OSes

### PR DESCRIPTION
**Pull request by jackdpeterson**
The purpose of this PR is to allow failed fstab entries to not cause an
OS to hang on boot. This is particularly problematic on cloud providers
like AWS where there is not a quick way to manage an instance and select
a skip option prior to SSH access becoming available.

### CODE REVIEW

**Comment by purpleidea** [comment]
@jackdpeterson Did you test this ;)

1) has arbitrary "Debian.yaml" entry in that file... It doesn't even syntax check :P
2) rename to misc_mount_nofail
3) resquash your changes into this commit (git commit --amend; git push whatever --force)
4) add Ubuntu yaml entry or ask @semiosis for a patch :)

**Comment by purpleidea** [comment]
And if anyone feels like it, please patch the travis-ci tester to check the data/*.yaml files for appropriate syntax too :)

**Comment by jackdpeterson** [comment]
@purpleidea Thanks for that -- copy-pasta error there as I'm not on my normal desktop w/ my puppet environment handy. Regarding the ubuntu.yaml file -- it inherits from debian so this should be sufficient to cover all debian based OSes including Ubuntu (correct me if I'm wrong) or if you prefer that I just have this at the ubuntu level and the override be added later.

**Comment by purpleidea** [comment]
@jackdpeterson You're right, I wasn't paying attention there, and the top level Debian.yaml is indeed the correct place.

LGTM, merged, thanks!

**Pull request merged**
